### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Svashtar** [SyeSoftware/voltex#1]
Hi,

I would like to test your gem, which is exactly what I need, but there is not much resources on it, so i thought maybe I would ask directly. Hope it is not a problem.

Currently my problem is that i am getting:
No route matches [GET] "/voltex"

Weird thing is I can see route defined and voltex_path helper works.
But as you can see it points to /voltex and i get an above error.

Am i missing something?

Thx

**Comment by Svashtar** [comment]
Also when i look at the list of all routes, i see:

edit_role_path	GET	/roles/:id/edit(.:format)	voltex/roles#edit
role_path	        PATCH	/roles/:id(.:format)	voltex/roles#update
                       PUT	/roles/:id(.:format)	        voltex/roles#update

But edit_role_path has an undefined method `edit_role_path' error.

**Comment by alejandrodevs** [comment]
Hi, can you show how your routes.rb looks like?

**Comment by Svashtar** [comment]
Sure, i've sent it to your gmail.

**Comment by alejandrodevs** [comment]
Maybe this solves the problem:
```ruby
mount Voltex::Engine, at: '/'
```

After that you should have the route `/roles/:id/edit` available and the `edit_role_path` helper.
Can you try it please?

**Comment by Svashtar** [comment]
```
ActionController::UrlGenerationError in Voltex::RolesController#edit
No route matches {:action=>"index", :controller=>"dashboard", :id=>"1"}
```

Also getting undefined method for edit_role_path

**Comment by alejandrodevs** [comment]
Can I see the backtrace please?

**Comment by Svashtar** [comment]
Sent it to gmail,
One is for undefined method and the other for when i try /roles/1/edit directly

**Comment by alejandrodevs** [comment]
There is no reason to be redirected to dashboard index action in voltex. Maybe some in your code is getting wrong. Check your before/after actions in application controller. Another option is you to create your own RolesController to update your permissions (accepting permissions_ids: []), the voltex core will work as usual.

Please let us know if you fix your issue.

**Comment by Svashtar** [comment]
Actually, even if I don't define any routes for Voltex, as soon as I enable Voltex it breaks something in relation to routes. I am using Passages gem for easy routes browsing, and this one is failing instantly after enabling Voltex. Maybe the error itself is not even related to routes.

What I didn't tell you yet is the fact that i am using Rolify along with Devise and CanCan.
So I think this for sure is something that could have an impact.

What i did is install VOltex according to your instructions, but i removed user migration which adds role_id to Users. I don't need this as I have users_roles table and rolify already up and running.
Next thing i need to change is has_many :permissions, through: :roles (instead of role).

I am pretty sure this is the root of the problems.
Did I oversimplify the impact of role_id in users table and is this something that is a must have?

Is it even possible to integrate Voltex with Rolify or should i remove Rolify altogether, create new role model with table, and have user just belong_to role? This way I would go from multi roles system to single role sistem (which i anyway already use effectively).

Of course I would loose some nice things Rolify brings to the table.

Thx

**Comment by alejandrodevs** [comment]
Are you still getting an error if you remove routes for Voltex and remove `before_action :set_current_permissions` from your application controller?

**Comment by Svashtar** [comment]
Yes, as soon as i enable voltex gem and initializer.

**Comment by Svashtar** [comment]
Hey. I have figured out everything, and works perfectly now. Well, i am using my own routes, but all well.
I do have another question though.

Is it possible to include non-restful resource, used when there is no actual model, but i have manual authorize! :action, :object

Thx
