### ISSUE TITLE
Rails 5 Depreciation Warning

### ISSUE THREAD

**Issue by Svashtar** [SyeSoftware/voltex#2]
Hi,

I upgraded my app to Rails 5, and just wanted to let you know that i am getting depreciation warning:

DEPRECATION WARNING: Passing the separator argument as a positional parameter is deprecated and will soon be removed. Use `separator: '_'` instead. (called from block (2 levels) in <module:Setup> at /home/XXX/.rvm/gems/ruby-2.4.0@rails5/gems/voltex-0.0.6/lib/voltex/setup.rb:40)

Please, when you have time for new release :)

**Comment by alejandrodevs** [comment]
Hi. We'll fix this deprecation as soon as possible.
Thank you for let us know.

**Comment by alejandrodevs** [comment]
Now, you can upgrade to 0.0.7.
We are a CHANGELOG.md file to future versions.
Thank you.
