### ISSUE TITLE
current role

### ISSUE THREAD

**Issue by Sahar-Remodeling** [SyeSoftware/voltex#3]
Hello, I want to ask if there a ready method to get direct to the current role?

**Comment by alejandrodevs** [comment]
Hi, I'm not pretty sure what you mean, but if you want to get the role of the current user you can get it from your user instance like this...

```ruby
user = User.first
user.role  # => the user's role.

# If you are using some authentication gem like devise you can
# get the role from your controllers like this...

class SomeController < ApplicationController
  def index
    current_user.role # => current user's role
  end
end
```

I hope it can help you.

**Comment by Sahar-Remodeling** [comment]
thanks, I already did as you said. 
I just thought may be after installing voltex, I can have the current role by just typing a keyword or method name like `current_role`!
never mind :)
