### ISSUE TITLE
multi roles for a user

### ISSUE THREAD

**Issue by Sahar-Remodeling** [SyeSoftware/voltex#4]
I know how exactly role stored in the database , as a column containing the role id in the `User` table.
But I need to know if there is a possibility to have multi roles per user? as this scenario is applicable in our business!
can the `set_current_permissions` get the permissions for the roles of the current user?

**Comment by Sahar-Remodeling** [comment]
I am thinking of having a new table called `user_roles` containing the roles for a user. and during the application running time the user can switch the role by a checklist that leading to change the `role_id` column in the user table of the current user.

What do you think?

**Comment by alejandrodevs** [comment]
Yes, It's possible and it's pretty simple.

You need to create the `roles_users` table. Your migration needs to look like this...
```ruby
create_table(:roles_users) do |t|
  t.references :role
  t.references :user
end
```

Change users relation to `has_and_belongs_to_many` in your role model...
```ruby
class Role < ApplicationRecord
  ...
  has_and_belongs_to_many :users
  ...
end
```

In your user model you need to change two things, your role relation needs to be `has_and_belongs_to_many` and your permissions relation needs to be through `roles` like this...
```ruby
class User < ApplicationRecord
  ...
  has_and_belongs_to_many :roles
  has_many :permissions, through: :roles
  ...
end
```

And the rest it's going to work as expected.
We are considering to support this as a configuration in the future.
I hope this can be helpful. Let us know.

**Comment by Sahar-Remodeling** [comment]
@alejandrodevs, Thank you very much. Yes it works as expected after I made the new association.

Appreciated :)
